### ISSUE TITLE
[Question ❓] How to install only "root/run" dependencies and ignore other groups dependencies

### ISSUE THREAD

**Issue by Mehdi-H** [paketo-buildpacks/poetry-install#180]
## General summary of the issue

I am suprised that running "pack build" with `paketo-buildpacks/poetry-install` installs all the dependencies described in my pyproject.toml file.

For production, I only want to install run dependencies (in `[tool.poetry.dependencies]` section), dependencies in other groups (such as `[tool.poetry.group.dev.dependencies]`) are not necessary and make the built image heavier than necessary

## Expected Behavior

When running `pack build [my_image] --builder paketobuildpacks/builder:base` (using `paketo-buildpacks/poetry-install` in Detection phase) I expect `paketo-buildpacks/poetry-install` to run the following command : 

`POETRY_CACHE_DIR=/layers/paketo-buildpacks_poetry-install/cache POETRY_VIRTUALENVS_PATH=/layers/paketo-buildpacks_poetry-install/poetry-venv poetry install --only main`

Having the following dependencies in pyproject.toml, I expect only fastapi and uvicorn to be installed, without pytest ✅  : 

```TOML
[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.100.0"
uvicorn = {extras = ["standard"], version = "^0.23.1"}


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
```

## Current Behavior

When running `pack build [my_image] --builder paketobuildpacks/builder:base` (using `paketo-buildpacks/poetry-install` in Detection phase), I see in the log that the following command is run :

`POETRY_CACHE_DIR=/layers/paketo-buildpacks_poetry-install/cache POETRY_VIRTUALENVS_PATH=/layers/paketo-buildpacks_poetry-install/poetry-venv poetry install`

Having the following dependencies in pyproject.toml, pytest is installed 😢  : 

```TOML
[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.100.0"
uvicorn = {extras = ["standard"], version = "^0.23.1"}


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
```

I see the following logs in the console : 

```plaintext
Paketo Buildpack for Poetry Install 0.3.16
  Executing build process
    Running 'POETRY_CACHE_DIR=/layers/paketo-buildpacks_poetry-install/cache POETRY_VIRTUALENVS_PATH=/layers/paketo-buildpacks_poetry-install/poetry-venv poetry install'
      Installing dependencies from lock file
      
      Package operations: 4 installs, 0 updates, 0 removals
      
        • Installing iniconfig (2.0.0)
        • Installing packaging (23.1)
        • Installing pluggy (1.2.0)
        • Installing pytest (7.4.0)
```

## Question

I don't see any configuration or environment variable to add arguments to "poetry install" command in the README.md file, is there something that I missed ?

## Steps to Reproduce

Tell me if this is necessary and I can setup a repository with reproducible steps, as it can take me some time to do it. I'll do it happily :)

## Motivations

> How has this issue affected you? What are you trying to accomplish? What is the impact? Providing context helps us come up with a solution that is most useful in the real world.

In the current situation, having poetry installing all dependencies, even the ones I do not need is a no-go for any of my projects in production.
